# The CI pipeline to allow user to merge branch on develop.

name: CI for develop branch

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  lint:
    name: Code formatting check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Make Gradle executable
        run: chmod +x ci-cd-example-1/gradlew

      - name: Run Spotless check (code format)
        working-directory: ./ci-cd-example-1
        run: ./gradlew spotlessCheck

  tests:
    name: Run unit tests with coverage
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Make Gradle executable
        run: chmod +x ci-cd-example-1/gradlew

      - name: Run unit test with coverage threshold (90%)
        working-directory: ./ci-cd-example-1
        run: ./gradlew clean test -Plimit=0.9

  clean_build:
    name: Clean build
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Make Gradle executable
        run: chmod +x ci-cd-example-1/gradlew

      - name: Run clean build
        working-directory: ./ci-cd-example-1
        run: ./gradlew clean build